### ISSUE TITLE
Do not see my kyl tokens

### ISSUE THREAD

**Issue by MarcoD6** [Kylin-Network/subport#11]
My adres is 0x66fAeC5558970f016f174A36bDa80C855dE12909

**Comment by ncodespot** [comment]
check this page(https://staking.kylin.network/stake/KYL)?

**Comment by STOOV1** [comment]
Hello
https://staking.kylin.network/stake/KYL
please copy and paste this into your ERC20 wallet browser for access to your Kylin.
