### ISSUE TITLE
Staked coins

### ISSUE THREAD

**Issue by Patrock2** [Kylin-Network/subport#13]
I can not access my staked KYL on your site.  On laptop the site does nothing after linking my wallet.   On mobile it gives a error.   Here is my metamask 0xBF8d0202915E2aCAd56d1f141e992A665dE11202

**Comment by ncodespot** [comment]
check this page(https://staking.kylin.network/stake/KYL)?

**Comment by Patrock2** [comment]
Same as before,  "an internal error has occurred "

**Comment by Patrock2** [comment]
How will i be contacted about this issue.  I was contacted on telegram but i pretty sure it was a scam.

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
Copy and paste this into your ERC20 wallet browser for access to your Kylin.

**Comment by Patrock2** [comment]
thank you
