### ISSUE TITLE
I can not withdraw kyl

### ISSUE THREAD

**Issue by Aljunibi** [Kylin-Network/subport#14]
I can't withdraw my coins Kylin Price (KYL)

Available at https://www.kylin.network .. staking (ETH-KYL)

Wallet address: 0x313Df0D904dAb4C590ff66E3b43d8F5d185b8cD4

**Comment by ncodespot** [comment]
hi @Aljunibi , can you make a screenshot of the staking page connected with your wallet(0x313Df0D904dAb4C590ff66E3b43d8F5d185b8cD4)?

**Comment by ncodespot** [comment]
> I can't withdraw my coins Kylin Price (KYL)
> 
> Available at https://www.kylin.network .. staking (ETH-KYL)
> 
> Wallet address: 0x313Df0D904dAb4C590ff66E3b43d8F5d185b8cD4

hi @Aljunibi , can you make a screenshot of the staking page(https://staking.kylin.network/stake/KYL) connected with your wallet(0x313Df0D904dAb4C590ff66E3b43d8F5d185b8cD4)?

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
Hello
Please copy and paste this into your ERC20 wallet browser for access to your Kylin.
