### ISSUE TITLE
Do not see $KYL to unstake

### ISSUE THREAD

**Issue by phuocthaoins** [Kylin-Network/subport#16]
ETH Address: 0x562cc3cc48bbd1d33819a77a50beab689e90e6ba
Transaction Hash:
0x0686f13550a9a0e87086443971d98d0807d1fea8ae4eea1a9178adb97e010e14
Block:
 [14243009](https://etherscan.io/block/14243009)
ERC-20 Tokens Transferred:
 7,000.5907928006445

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
Hello
Copy and paste this into your ERC20 wallet browser to have access to your Kylin.
