### ISSUE TITLE
I can't see my kyl token on Stake platform!!! 

### ISSUE THREAD

**Issue by fethee** [Kylin-Network/subport#18]
Hello kylin!! My names Feti Savran.. 
![Screenshot_20221021_155518_com wallet crypto trustapp](https://user-images.githubusercontent.com/43237542/197200812-8336bf78-fd94-41dd-8ad2-44654abdc1cc.jpg)

My ERC - 20 walllet adresses

0x5EfC11d83efc6aE205a08E69c24ec79E7828743A

I transferred from exchange to exchange to stake my tokens and lost a lot of tokens without staking.

And now I see again that I don't have any tokens...

I invested $20,000 in trusting you so much, but this is not nice I've come across.

I can't benefit from the Pichu airdrop either because my tokens don't appear in my wallet address.

There are some pictures on my wallet (kyl transfers  you can see) 
![Screenshot_20221021_155223_com wallet crypto trustapp](https://user-images.githubusercontent.com/43237542/197200540-62e3f0bf-e990-4942-a750-e39711464f63.jpg)
![Screenshot_20221021_155221_com wallet crypto trustapp](https://user-images.githubusercontent.com/43237542/197200583-c8911530-5d4d-4cb9-b98a-d80b18b4deee.jpg)

**Comment by STOOV1** [comment]
Hello
https://staking.kylin.network/stake/KYL
please copy and paste this into your ERC20 wallet browser. Your Kylin will be accessible there.
