### ISSUE TITLE
Filled in the wrong substrative adress

### ISSUE THREAD

**Issue by JE345** [Kylin-Network/subport#2]
Hello guys,

I screwed up. 

Did the handshake for the PCHIU airdrop. 

But i filled in my Ethereum adress at the substrative adres line. 

That should have been my polkadot adress ....  

How can i correct this ? 

If i do the handshake again, and fill in the right adresses. It says error. But i can click "send another".  Will i correct my mistake with that? 

Regards, Erik

**Comment by sylvaincormier** [comment]
Hi Erik, 
I will contact the dev 
to see if we can do anything about this.
In the meantime, could you please post the concerned addresses?
Thank you!

**Comment by JE345** [comment]
My ether address is 0xD6009b6A5F9dBeeA3CdaC73af649C662a5d9bdE3

Thank you.

**Comment by razvanpopadev** [comment]
> Erik

Hi Erik,
Please resubmit your airdrop request with the correct substrate address. 

Regards,
Razvan

**Comment by donuttos** [comment]
Hi team have the same issue, I send my kyl to stake, and now I dont see my KYL.

This is the Hash of the staking transaction : 0x8a0d0cd5e4fdd7fafc1129e23ad15ec45f7cba349ef24a13c4522774fe34be56

Also I just submitted my pichiu airdrop, with my KYL staked, would that affect my airdrop amount?
Eth: 0x4208811902feBd12E624721C6D81D2a081da738B
Polkadot/substrate wallet, Pichiu Network: 5DqXGNFFRNn89zCrTSj8VSh2auxHnBr1FT29femG6rMUfzur

**Comment by JE345** [comment]
> > Erik
> 
> Hi Erik, Please resubmit your airdrop request with the correct substrate address.
> 
> Regards, Razvan

Thank you

Regards, Erik
