### ISSUE TITLE
Can't unstake my Kyl

### ISSUE THREAD

**Issue by AndyH1986** [Kylin-Network/subport#22]
Update!!!!

could withdraw my token via this link: https://staking.kylin.network/stake/KYL

---------------------------------------------------------------------
Hi Kyl-Team,

I dont see my staked tokens so i can't withdraw, please fix this error and send my tokens back (+ staking reward) back to my eth adressen.

ETH Address: 0x5cB99990e325DB1139990E1864B1E5f8Ec7ab839

58,825.05636949982 Kyl staked

tx_hash: 0xe69aad567a2390684b9dd8cdbda0e1c7d13541330808665bf603f7a841f43d83
Block: 14231744

<img width="984" alt="image" src="https://user-images.githubusercontent.com/56310284/197343272-35c82a2d-1290-4ad0-871d-b150c624eec8.png">

---------------------------------------------------------------------

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
please copy and paste this into your wallet browser, your Kylin is accessible here.
