### ISSUE TITLE
Parachain Kylin Parallel contribution

### ISSUE THREAD

**Issue by CryptoKeijzer** [Kylin-Network/subport#23]
Hello, I joined the Kylin parachain through the Parallel platform. I still haven't received a KYL from that. I have already been in contact via Telegram with both parties who point to each other that certain steps are not being performed properly. I try to get extra attention in these ways. I have been in contact via Telegram with Kylin admins since September 21 but still no solution. Progress is always made, but then it gets stuck again that the KYL are not sent. Both parties always say that the other is responsible for sending the coins. I hope there is finally a solution to this.

**Comment by sylvaincormier** [comment]
Hi CryptoKeijzer.
Thanks for reaching out to us.
Not all parachains are dealing with the rewards the same way.
We were not familiar with Parallel's way of doing things. 
We are attending to this at the moment.
Thank you for your patience while we figure out the best way to do this.
We hope to get you your rewards very soon.

**Comment by CryptoKeijzer** [comment]
> Hi CryptoKeijzer. Thanks for reaching out to us. Not all parachains are dealing with the rewards the same way. We were not familiar with Parallel's way of doing things. We are attending to this at the moment. Thank you for your patience while we figure out the best way to do this. We hope to get you your rewards very soon.

Thanks for your comment. I've been hearing this response since September 21, that is, since I've been in contact with Bas via telegram. Both sides both Kylin and Parallel keep saying that the other has to take steps but you can't figure it out so far. Parallel says they haven't received KYL yet. Can't Kylin manually send me the KYL if of course I prove I've participated in the parachain?

**Comment by sylvaincormier** [comment]
Hi CryptoKeijzer.
Here are some more detailed explanations.
Parallel has used a sovereign account to register users to the crowdloan.
As a result, the rewards were automatically sent to the 
corresponding account on Kylin,
to which they claim not to have access.
We have never handled a situation like this.
We have agreed with Parallel that we were going 
to take the steps to resolve this as much as we can from our end.
We cannot access these funds "manually" because these funds 
were allocated through a "decentralized" process.
We value the importance of these rewards and regret this delay.
This is a complicated problem and we are working to get it resolved asap.

**Comment by CryptoKeijzer** [comment]
I am familiar with this problem Bas from your team told me via telegram. You could also ask him for information which I have received from Parallel as answers. They say there is nothing more they can do and are waiting for what Kylin is going to do next. If both teams wait for steps from each other, this will be a very long process.

**Comment by CryptoKeijzer** [comment]
> Hi CryptoKeijzer. Here are some more detailed explanations. Parallel has used a sovereign account to register users to the crowdloan. As a result, the rewards were automatically sent to the corresponding account on Kylin, to which they claim not to have access. We have never handled a situation like this. We have agreed with Parallel that we were going to take the steps to resolve this as much as we can from our end. We cannot access these funds "manually" because these funds were allocated through a "decentralized" process. We value the importance of these rewards and regret this delay. This is a complicated problem and we are working to get it resolved asap.

I am familiar with this problem Bas from your team told me via telegram. You could also ask him for information which I have received from Parallel as answers. They say there is nothing more they can do and are waiting for what Kylin is going to do next. If both teams wait for steps from each other, this will be a very long process.

**Comment by sylvaincormier** [comment]
Your rewards have been sent

**Comment by CryptoKeijzer** [comment]
> Your rewards have been sent

Thanks for the support. I have received the KYL.
