### ISSUE TITLE
Pchu airdrop not received 

### ISSUE THREAD

**Issue by Jlaw22** [Kylin-Network/subport#24]
Hi

I completed the handshake for the Pchu airdrop however haven’t received the tokens in Nova wallet. Please can you advise if there are any issues? 

Thanks!

**Comment by razvanpopadev** [comment]
Hi!
Please let me know you ERC20 address and the substrate address used for the handshake. Thank you!

Regards,
Razvan

**Comment by Jlaw22** [comment]
Hi the addresses used for the handshake are 

0xf1E7E21c0CaDb0Bec3Fb4D0415C298675f7DC0d1

12koU1sM9yLXVcr4w3a1KkV8q8uZLgLwnJrmY3pxhkWP32RK

Thank you!

**Comment by razvanpopadev** [comment]
Hello @Jlaw22 
Your tokens had been transferred to substrate based address 12koU1sM9yLXVcr4w3a1KkV8q8uZLgLwnJrmY3pxhkWP32RK Pleace check the balance by connecting to Pichiu Network https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts

Regards,
Razvan
