### ISSUE TITLE
Pichu airdrop not received enough

### ISSUE THREAD

**Issue by LaraSchoen** [Kylin-Network/subport#25]
Hi there
I have 2 erc20 addresses with KYL.
0xA2C848B395d072F97aF93bb4766c6C31D5Aa1D4E  - 122k KYL
0xAFbAa946dcB78DEcBD32B475F8F1Ab2268dCDf40  -  106k KYL

Did  a handshake with both wallets via 1 option to my substrate wallet.  Airdrop website showed me messages that I am eligible for the 2 airdrops.
Only received 4150 PICHU for 1 wallet with 122k KYL (0.034 PICCHU for KYL) instead of 7754 PICHU for 122k+106k my KYL wallets.

my substrate address 
5EHLckyHPosi8dD5jQS2sbyCbdjnMyUjmrNtZNDCvxXBRJVM

**Comment by razvanpopadev** [comment]
> 5EHLckyHPosi8dD5jQS2sbyCbdjnMyUjmrNtZNDCvxXBRJVM

Hi Lara, 
This issue had been solved, please confirm.

Regards,
Razvan

**Comment by LaraSchoen** [comment]
Hi Razvan

Confirmed.
Many thanks
