### ISSUE TITLE
change my Substrate Address

### ISSUE THREAD

**Issue by SatoshiHelloMotto** [Kylin-Network/subport#26]
Hello can i change my Substrate address for my metamask instead in Js.extension i will use the NovaWallet address for Pichiu since it will have lock drop rewards every month of .5% equivalent for 5% for 10months?

**Comment by razvanpopadev** [comment]
Hello,
For the current airdrop the substrate address cannot be changed, only for future airdrops that are going to be officially announced. 

Regards,
Razvan
