### ISSUE TITLE
PCHU tokens not received

### ISSUE THREAD

**Issue by MglMogul** [Kylin-Network/subport#27]
My ETH address is 0x01B30CA1bDDE1F68ABe69c46FE88f79B496EC63a and I filled out the option 1

My polkadot.js address is 5F417PRaFuGHyW8VAuo9drppwjYt44NZ8tEZEcgFiFaH1LgX 

But there is no PCHU token still.

**Comment by STOOV1** [comment]
Hey MglMogul
Please set your Network to Pichiu and then in SETTINGS update your Metadata. Your airdrop amount should then get refreshed.

**Comment by razvanpopadev** [comment]
> My ETH address is 0x01B30CA1bDDE1F68ABe69c46FE88f79B496EC63a and I filled out the option 1
> 
> My polkadot.js address is 5F417PRaFuGHyW8VAuo9drppwjYt44NZ8tEZEcgFiFaH1LgX
> 
> But there is no PCHU token still.

Hi!
You've submitted ETH address and H9XBwKCg1agWnjnFnnqwqkhtuSyZrrzJiJwQCfWTg95XRHX (equivalent to 5GduXcyL3eZkm8vLV5yo3tPhkKAjmC3orLUC1YPYysvanDbT prefix 42), your PCHU tokens were sent into this address.

Regards,
Razvan

**Comment by MglMogul** [comment]
Oh, I see it now
Thank you
