### ISSUE TITLE
Pichu Airdrop not received

### ISSUE THREAD

**Issue by jasonDeutsch214** [Kylin-Network/subport#28]
I completed option 1 on the the airdrop site with my metamask and polkadot.js extension and it looks like I did not receive the tokens. I used the Allow access to all chains address not sure if there is another I should have added. 

Metamask address 

0x18235d6eB8b7Fdbd6fDBb45eDBA4b2c485cDabDF

Polkadot.js address
5EoFoNWF42P6nLeGmZwUYw3CjVRwn94LDLHoH9WoSABNMeVF

**Comment by STOOV1** [comment]
Hello jasonDeutsch214
Please make sure you are in the correct Pichiu Network and that you’ve updated your Metadata in SETTINGS. This should do the trick.

**Comment by razvanpopadev** [comment]
Hello @jasonDeutsch214 
You should see the tokens inside address Polkadot.js address 5EoFoNWF42P6nLeGmZwUYw3CjVRwn94LDLHoH9WoSABNMeVF on Pichiu Network, as @STOOV1  stated earlier there should be a network selection issue (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpichiu-rococo-01.onebitdev.com#/utilities) I've just checked and the airdrop was already transferred to you. 

Regards,
Razvan
