### ISSUE TITLE
PCHU tokens not received

### ISSUE THREAD

**Issue by ZeHungryBear** [Kylin-Network/subport#29]
Hey, I did the handshake and got the confirmation the other day but do not see the airdrop tokens. I provided my ETH address where I have my KYL stored but I'm worried I may have messed up on the Polkadot.js side. I provided the substrate address that was linked to my Dot wallet I'm worried I didn't do the right thing. 
Please help ! :(

**Comment by STOOV1** [comment]
Hey ZeHungryBear
Please check that your are in the correct Pichiu Network and the in SETTINGS you’ve updated your Metadata. This should show your airdrop amounts.

**Comment by ZeHungryBear** [comment]
Hi @STOOV1 
Thank you for your reply. I switched to the PICHIU / Kusama parachain but do not see anything. I even created a new PCHU account in there but nothing. 

When I did the handshake, I synced my ERC-20 KYL wallet and I copied the polkadot.js substrate address in which I had my DOT, ( EvmqpU5rFwiJ4GFcwzsSdni9NYsahWva1UEBx3LTQQGXBHj ), it said registration/handshake successful - did I make a mistake ? 
That's what I understood from the guide and I'm worried I messed up. I can provide both addresses for verification.

**Comment by razvanpopadev** [comment]
Please send me here your ETH address used. Thank you!

**Comment by ZeHungryBear** [comment]
Hey @inodelisia,

I used 0x43d4A8A224a77b4FD1f9F205062bA718964B32F2 as the ETH wallet address.

**Comment by razvanpopadev** [comment]
> 

You already have the airdrop tokens into substrate address 13MTKqPH5gCFywTKotEpgqFrrQGHULFtC8MxxakjXhDHxWND. As mentioned here https://github.com/Kylin-Network/subport/issues/29#issuecomment-1289495076 please check your network selection under PolkaJS interface (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpichiu-rococo-01.onebitdev.com#/accounts).

Regards,
Razvan
