### ISSUE TITLE
Can not withdraw KYL staked. Please help.

### ISSUE THREAD

**Issue by sonpham2807** [Kylin-Network/subport#3]
Hi team,
I can not withdraw KYL staked to my metamask. It always looks like pending when I click "Withdraw all"

Here is my address 
0xD1cD21C1C90Cdc77781086f193F98BC8BaC9392f

![image](https://user-images.githubusercontent.com/116014593/196212601-a82be767-c460-4fab-a86c-5cf65d959f89.png)

Please help me check.

**Comment by sonpham2807** [comment]
hello, 7 days later and everything is still the same. Anyone can help ?

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
please see this site for access to your Kylin.

**Comment by sonpham2807** [comment]
Hey,
Of course I know this website https://staking.kylin.network/stake/KYL
You can see in the picture attached on my first message.
I see so many people have the same issue on github
Please provide some useful help  so that we can withdraw KYL to our wallet.
Thanks
