### ISSUE TITLE
Did not receive PCHU airdrop. 

### ISSUE THREAD

**Issue by JE345** [Kylin-Network/subport#30]
Did not receive any PCHU. 
Did option 1 

Ethereum address: 
0xD6009b6A5F9dBeeA3CdaC73af649C662a5d9bdE3

Substrate address: 
16cwUFmh2ossPU1af3NezbnPKyCJh1BGSemGUK4MNmepXhJs

Thank you.

**Comment by STOOV1** [comment]
Hello JE345
Can you check and see if you have an update of your Metadata in SETTINGS in Polkadot JS. Be sure also you are in the correct Pichiu Network.

**Comment by razvanpopadev** [comment]
> 

Hello,
We couldn't find any address mention in your request as a successfully completed handshake process. When exactly did you made the handshake and what was the URL used for that?

Regards,
Razvan

**Comment by JE345** [comment]
Thanks for your reply.
I am using Nova wallet ? Not Polkadot JS 

That is strange .. i did do the handshake. 
First time it went wrong, because i entered my ethereum adres in the substrate section. I asked and here at github they said that i could try the handshake again. So i did, but i cant remember when, i think it was 19 or 20 october.

Regards, JE

**Comment by razvanpopadev** [comment]
I'm sorry @JE345  I couldn't identify your airdrop request based on the info you mentioned here. Please try to remember the ETH address where KYL token are stored and the substrate address used. 

Regards, 
Razvan

**Comment by razvanpopadev** [comment]
Also the KYL tokens balance on 0xD6009b6A5F9dBeeA3CdaC73af649C662a5d9bdE3 is 0
