### ISSUE TITLE
Staking KYL website is down 

### ISSUE THREAD

**Issue by H2O71** [Kylin-Network/subport#31]
**Hi, any Kyl staking website is down. I can't get to my KYL token not to mention an attempt to register for air drop.** I would appreciate any further tips.

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
Please copy and paste this into your wallet browser, your Kylin is there to access.

**Comment by STOOV1** [comment]
Sorry that the airdrop has been distributed.
