### ISSUE TITLE
Cannot unstake my kyl

### ISSUE THREAD

**Issue by Henryasc** [Kylin-Network/subport#32]
I have tried for so many days to unstake my kyl and my rewards, but i have not been able to. I also was not able to register my trust wallet to receive pcchu tokens.  I just dont want to lose my kyl tokens. 
My address is:
0x498235B0b66111c8805C409B56F0D7d37DC24ceC
Thanks so much!

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
please copy and paste this into your wallet browser. Your Kylin will be there.
