### ISSUE TITLE
Can't access the website and didn't receive the airdrop

### ISSUE THREAD

**Issue by Johan8888** [Kylin-Network/subport#33]
Hi,  staking KYL website is down, how can i withdraw KYL.

I completed option 1 on the the airdrop site with my metamask and polkadot.js extension and it looks like I did not receive the tokens.

Metamask address
0x5Ac33F16AC10db83f78C1e9bFa0b078d390856C2

Polkadot.js address
F4nwSWd8TTpAtP5tozGSSXtav95hPjLsdiSoFbLPnwxeNt7

Please check my account.

**Comment by STOOV1** [comment]
Hello Johan8888
https://staking.kylin.network/stake/KYL
You can access your Kylin here. To see your PCHU be sure your in the correct Network and you’ve updated your Metadata in SETTINGS on Polkadot js.

**Comment by razvanpopadev** [comment]
Thank you @STOOV1 ! @Johan8888 your issue has been solved, please confirm.
Regards,
Razvan

**Comment by Johan8888** [comment]
Thanks for your help. I have withdrawn my KYL and saw PHCU in my wallet.
