### ISSUE TITLE
PCHU airdrop not (yet) received 

### ISSUE THREAD

**Issue by Kazzimotto** [Kylin-Network/subport#35]
Please let me know what you need from my side. 

Thx

**Comment by razvanpopadev** [comment]
Please send here your erc20 address, where KYL tokens are hold and your substrate address.

**Comment by Kazzimotto** [comment]
Hello,

My ETH address: 0x964D2B94505CC9491C45400e6CEaF8cDe14233a9
My Kusama address: Ff2ou9Kiw2zPem6eU2Nq1oUKXPGwSeg43o74sAwAfbFHqjz

Many thanks lor looking into it.

**Comment by razvanpopadev** [comment]
> 

Thank you ! You handshake was done using substrate address 138uFPBTo95jvfbRAmjJBgw3GYceW3myGkxLUp8wSPKcFCxe (a Polkadot address with prefix 0) 202 PCHUs were sent to this address as an airdrop.

Regards,
Razvan

**Comment by Kazzimotto** [comment]
Many thanks for confirming.

This is my Polkadot on Ledger address (I think that a wrongly put that address in), does that mean the PCHU will be lost, since it is not Kusama address?

And how can I interact with PCHU on Ledger, is there an App for this already?

Thx.

**Comment by razvanpopadev** [comment]
Please try those instructions: https://support.ledger.com/hc/en-us/articles/360016289919-Polkadot-DOT-?docs=true

**Comment by Kazzimotto** [comment]
Hi,

The link provided talks about how to create or connect a Polkadot account into polkadot.js. This I have done already a while ago, but I have no means of changing network to select PCHU or anything else but Polkadot Network, under the polkadot.js web extension. 

So the question is now, when can I expect to see an app for Pichiu under Ledger, that will allow me to interact with my PCHU tokens?

Thx.
