### ISSUE TITLE
I am yet to receive my pichu airdrop 

### ISSUE THREAD

**Issue by Toby-z** [Kylin-Network/subport#36]
Hi
Thank you for attending to my query. 
i had my handshake done on the 21st Oct 2022. 
I understand that the pichu airdrop has already happened for Kyl holders. 
unfortunately, I have not received mine. 
Are they coming in batches? If not kindly advice. 
thank you.

**Comment by STOOV1** [comment]
Hello
Please make sure you are in the correct Network in Polkadot js and in SETTINGS you’ve updated your Metadata.

**Comment by razvanpopadev** [comment]
> Hi Thank you for attending to my query. i had my handshake done on the 21st Oct 2022. I understand that the pichu airdrop has already happened for Kyl holders. unfortunately, I have not received mine. Are they coming in batches? If not kindly advice. thank you.

Hello @Toby-z !
Please send us you ETH address and substrate address submitted in the handshake. 

Regards,
Razvan

**Comment by Toby-z** [comment]
Thank you Razan for getting back. 

Here is my eth address : 0xfe84C5E4fBDB16Ff4A3eF6B54B7278c172e4d2b4

Also my substrate address : GyDBmX6EawjbRGALKaZfgjnXTnc7QDXxMSWZVNUjdAuRu1X.

**Comment by razvanpopadev** [comment]
Hello @Toby-z 
Your substrate address GyDBmX6EawjbRGALKaZfgjnXTnc7QDXxMSWZVNUjdAuRu1X is invalid please send another correct address https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts

Regards,
Razvan
