### ISSUE TITLE
how can i see my pchu in polkadot.js

### ISSUE THREAD

**Issue by martijn197547** [Kylin-Network/subport#38]
![Schermafbeelding 2022-10-24 134751](https://user-images.githubusercontent.com/116562212/197518795-4420f8f3-b8f3-42aa-a4b3-cfaca127e70c.jpeg)
hello, i did option 2 according to the manual, this is including the handshake as far as I know. correct?
i dont know how to see my pchu in polkadot.js or can i use a mobile software wallet (witch one?) to see pchu?

can you help me please?

**Comment by inodelisia** [comment]
Hello! Please send me your substrate address and also the ETH address where KYL tokens are hold.

Thank you,
Razvan

**Comment by razvanpopadev** [comment]
> ![Schermafbeelding 2022-10-24 134751](https://user-images.githubusercontent.com/116562212/197518795-4420f8f3-b8f3-42aa-a4b3-cfaca127e70c.jpeg) hello, i did option 2 according to the manual, this is including the handshake as far as I know. correct? i dont know how to see my pchu in polkadot.js or can i use a mobile software wallet (witch one?) to see pchu?
> 
> can you help me please?

Hello! Please send me your substrate address and also the ETH address where KYL tokens are hold.

Thank you,
Razvan

**Comment by STOOV1** [comment]
Hello 
Make sure you have the correct Network-Pichiu and in SETTINGS you’ve updated your Metadata.

**Comment by martijn197547** [comment]
> > ![Schermafbeelding 2022-10-24 134751](https://user-images.githubusercontent.com/116562212/197518795-4420f8f3-b8f3-42aa-a4b3-cfaca127e70c.jpeg) hello, i did option 2 according to the manual, this is including the handshake as far as I know. correct? i dont know how to see my pchu in polkadot.js or can i use a mobile software wallet (witch one?) to see pchu?
> > can you help me please?
> 
> Hello! Please send me your substrate address and also the ETH address where KYL tokens are hold.
> 
> Thank you, Razvan

hello,

ETH adress: 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55
substrate addres: 15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW

**Comment by martijn197547** [comment]
> Hello Make sure you have the correct Network-Pichiu and in SETTINGS you’ve updated your Metadata.

hello,

can you tell me how to select Network-Pichiu ?

thx

**Comment by razvanpopadev** [comment]
Hello @martijn197547 !
I was unable to find the Option 2 submitted into our requests database neither with address  0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 or 15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW. Also address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55  has no KYL tokens hold.

**Comment by martijn197547** [comment]
> Hello @martijn197547 ! I was unable to find the Option 2 submitted into our requests database neither with address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 or 15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW. Also address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 has no KYL tokens hold.

i don't understand:
0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 (adres trust wallet eth)

15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW (signed message)

0x6882b79cafa5b930da8646789e23f1922e360b3f249c9f2a6f4bdf14c2482e891e37c158c8722ee5deb91f9e94c593ca39befe54b81e363cf6fcf4255667b4111c (signature hash)

i did option 2: https://airdrop.kylin.network/assets/Option%202%20DEMO.mp4
![Schermafbeelding 2022-10-26 092324](https://user-images.githubusercontent.com/116562212/197961144-0c7ab67f-5534-4995-a73e-7efb613830d0.jpeg)

i get the message that it was ok.
