### ISSUE TITLE
Handshake

### ISSUE THREAD

**Issue by Avtostoritve** [Kylin-Network/subport#39]
Hi guys. Can you please check if my handshake was made correctly. If not, is there anything that can be done after airdrop is closed? 
Thank you.

My erc20 address is 0xe932D1f8D557834e2252421b0F965ed22f10c515. Transaction hash is: 0xfd1f071305749c00c0ad53745f51f500a004fd4431c9023f58658387880ac2ca

My polkadot address is 
14Qqn2KmUqVoCC1xH1oyaYQy5EZ6dAzogcZpiW5zDv2bbFDC

**Comment by STOOV1** [comment]
Please try and update your Metadata in your Polkadot JS extension under settings.

**Comment by razvanpopadev** [comment]
> 14Qqn2KmUqVoCC1xH1oyaYQy5EZ6dAzogcZpiW5zDv2bbFDC

Hi @Avtostoritve !
Issue has been solved, please confirm!

Regards,
Razvan

**Comment by Avtostoritve** [comment]
Hello guys. You made it. I can see my airdrop tokens now. 
Razvan, you are the MAN! Great respect to all of you guys.

Wishing you all the best.
