### ISSUE TITLE
Handshake verification

### ISSUE THREAD

**Issue by AshF1** [Kylin-Network/subport#4]
Hi guys, Please can you confirm if I have completed the handshake correctly? My pichu address is 5DvZbtodk7NiBV2FyxNdLabjMaArFMqfHMzDJnvhK2PgT1ge

Eth address: 0x8D3D26E0012bf36486CbD282FBfad92147259877

Thank you.

**Comment by razvanpopadev** [comment]
> Hi guys, Please can you confirm if I have completed the handshake correctly? My pichu address is 5DvZbtodk7NiBV2FyxNdLabjMaArFMqfHMzDJnvhK2PgT1ge
> 
> Eth address: 0x8D3D26E0012bf36486CbD282FBfad92147259877
> 
> Thank you.

Hi,
Your handshake is correct, paired with 5DvZbtodk7NiBV2FyxNdLabjMaArFMqfHMzDJnvhK2PgT1ge on 2022-10-17 15:48:18.

Regards,
Razvan
