### ISSUE TITLE
Airdrop not visible?

### ISSUE THREAD

**Issue by kimvisser** [Kylin-Network/subport#40]
Hi, I checked to see if the airdrop arrived at my account but balance is 0 pchu for "Pichiu for Kylin network" on Kusama & parachains. Mayby I am doing something wrong, no clue. 

I am using this link with my polkadot js extention in browser. 

polkadot account address 5DRSAyg6VbHUGUMr4UV8kKf55eBvKWXe3W6J115G9YPJvFiG
eth metamask address 0x7ee1520a15B07A9EF7E714cEc549f7eF14B7A5EF

I have my Kylin staked in https://staking.kylin.network/stake/KYL

Love to hear from you. 
Best regards! 
Kim

**Comment by razvanpopadev** [comment]
> Hi, I checked to see if the airdrop arrived at my account but balance is 0 pchu for "Pichiu for Kylin network" on Kusama & parachains. Mayby I am doing something wrong, no clue.
> 
> I am using this link with my polkadot js extention in browser.
> 
> polkadot account address 5DRSAyg6VbHUGUMr4UV8kKf55eBvKWXe3W6J115G9YPJvFiG eth metamask address 0x7ee1520a15B07A9EF7E714cEc549f7eF14B7A5EF
> 
> I have my Kylin staked in https://staking.kylin.network/stake/KYL
> 
> Love to hear from you. Best regards! Kim

Hi Kim,
Issue is solved now, this was caused by the fact that the KYLs tokens were staked not hold in the account used handshake. 

Regards,
Razvan
