### ISSUE TITLE
NO PCHU AIRDROP

### ISSUE THREAD

**Issue by aesthetist** [Kylin-Network/subport#41]
possible accounts in order airdrop should have went to:

5CRoBfg3KrAjvrRDxcGvHnSx9Zsh7RTMgJmHJcBQGNHkmhU6

5G7Q6kHRcowDcmPpiftsKAPuxBokGrWXauDa6WGq9hNdF85J

5EfB19MXSo5XpgXU33fCQVcpBDrFmBoVd1i3CKPcZyEwBvf5

not sure which one was the correct since I had issues creating and submitting for airdrop

**Comment by STOOV1** [comment]
Have you updated your Metadata?

**Comment by STOOV1** [comment]
You can check in settings in your JS extension.

**Comment by aesthetist** [comment]
how do you do that?

**Comment by aesthetist** [comment]
*Polkadot/Substrate Portal - 24 October 2022* - Watch Video
<https://www.loom.com/share/ad0cbfe2191c475a985d47c32118d798>
<https://www.loom.com/share/ad0cbfe2191c475a985d47c32118d798?utm_medium=gif>

**Comment by razvanpopadev** [comment]
> 5CRoBfg3KrAjvrRDxcGvHnSx9Zsh7RTMgJmHJcBQGNHkmhU6

Hello @aesthetist !
This was the address used for the handshake: 5CRoBfg3KrAjvrRDxcGvHnSx9Zsh7RTMgJmHJcBQGNHkmhU6. Please check this one and confirm. Thank you!

Regards,
Razvan

**Comment by aesthetist** [comment]
got it now! thx!
