### ISSUE TITLE
No PCHU airdrop 

### ISSUE THREAD

**Issue by dacle9** [Kylin-Network/subport#43]
Hello, I did not received the airdrop. 

I did the handshake with the following address:
0x598F067eb982b38789ef3f4eFde657B319511418

Had KYL staked.

How to proceed ? 

Many thanks,

**Comment by dacle9** [comment]
@inodelisia

**Comment by razvanpopadev** [comment]
> Hello, I did not received the airdrop.
> 
> I did the handshake with the following address: 0x598F067eb982b38789ef3f4eFde657B319511418
> 
> Had KYL staked.
> 
> How to proceed ?
> 
> Many thanks,

Hello @dacle9 
Issue had been solved, please confirm.  Thank you!

Regards,
Razvan

**Comment by dacle9** [comment]
Solved indeed :), 

Many thanks @inodelisia , have a great day,

Cyril

**Comment by razvanpopadev** [comment]
Same to you Cyril!
