### ISSUE TITLE
i don't see my tokens 

### ISSUE THREAD

**Issue by giannissanto** [Kylin-Network/subport#44]
hi i cant see my tokens in the staking 
my address on  Metamask wallet is : 0x1A7138FC2992a04e8F13f5a9C0116787259C47aE

**Comment by razvanpopadev** [comment]
Hello @giannissanto !
I couldn't find you address, please send me your substrate address used for fulfilling the handshake.

Regards,
Razvan

**Comment by giannissanto** [comment]
Hi Razvan, can you help me how to find the substrate address I don't know many things.
Regards 
Giannis 

Στάλθηκε από το iPhone μου

> 25 Οκτ 2022, 15:36, ο χρήστης «Razvan P ***@***.***>» έγραψε:
> 
> substrate address

**Comment by razvanpopadev** [comment]
Hello @giannissanto 
During the moment you've did the handshake (on airdrop.kylin.network) you had to enter a substrate based address (or Pichiu Network address) for receiving the PCHU tokens into it.
