### ISSUE TITLE
Pichiu Tokens

### ISSUE THREAD

**Issue by TeeDubya1** [Kylin-Network/subport#45]
Hi
Sorry i cant seem to find my tokens.

ETH Address: 0xC4e75a1CA2EB5Ab0596F34e0ef934FAEF9A5C340

Substrate: 5G42VWcT6c8EtxKMu4QMpvBbYgbUFAzzaMfqeKVfSb3QX4Q4

Havent used Polkadot much so apologies if i am not looking in the right place or have the correct Polkadot.js settings

Thanks

**Comment by razvanpopadev** [comment]
Hello @TeeDubya1 
Please use the PolkadotJS interface connected to our network: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts
Your airdrop tokens had already been transferred.

Regards, 
Razvan

**Comment by TeeDubya1** [comment]
Thank you
