### ISSUE TITLE
Hi. I lost my Kyl tokens from staking, I don’t have them on my wallet either. What is the reason?  0xa7b0f9185506fD1f4E102ee7f3eBfd7C89883311 .... 101,718 KYL

### ISSUE THREAD

**Issue by aramis333** [Kylin-Network/subport#46]
Hi. I lost my Kyl tokens from staking, I don’t have them on my wallet either. What is the reason?  0xa7b0f9185506fD1f4E102ee7f3eBfd7C89883311 .... 101,718 KYL

**Comment by STOOV1** [comment]
Hello 
Please use this site to access your Kylin tokens.
https://staking.kylin.network/stake/KYL

**Comment by STOOV1** [comment]
Hello are you able to check this site and respond please.
