### ISSUE TITLE
Pichiu Holder Chart

### ISSUE THREAD

**Issue by LPatKylin** [Kylin-Network/subport#47]
I’m curious about current distribution. Is there a way to see pichiu holders and amounts similar to etherscan? I looked around but couldn’t find anything.

**Comment by razvanpopadev** [comment]
To be able to do that our CTO already started the process of joining subscan.io, but until the on-boarding is done it's possible to use an internal tool. I will get back with an URL as soon as the indexing process is done on Pichiu-Kusama.
