### ISSUE TITLE
Do not see / receive my Pichiu airdrop

### ISSUE THREAD

**Issue by Johanhake1** [Kylin-Network/subport#48]
Hi,

I do not see my Pichiu airdrop, can you check my handshake/help me further?

ETH: 0x70c93fA5961600e688Cd59668dF56927AcF69BD8
Substrate/kusama: CkE2vahgw6yWdLFnhWRXsYGsi5cv6sk6KJjebivFwTLtbi2

Thank you!

**Comment by razvanpopadev** [comment]
Hello @Johanhake1 
Please double check, your tokens are already transferred to your account, please be sure you are switching your wallet to Pichiu Network on Kusama relay chain. 

Regards,
Razvan

**Comment by Johanhake1** [comment]
Hi Razvan, thank you for confirming. 

I however have the issue with my subwallet interface that Pichiu is not yet an included network. To add I would need Pichiu's: Provider URL, network name and paraID. As I cant find these anywhere, could you help me with this?

Best,
