### ISSUE TITLE
I didn't receive the PCHU Airdrop

### ISSUE THREAD

**Issue by josvanotterloo** [Kylin-Network/subport#49]
Hi,

I didn't receive the PCHU airdrop on linked account: Hk5eJmc8GoBU8MhU3EHFAEvRkpwqkxfo2vJyEM8oW98dVZj
Address: 0x5072d9e034b97d32af8f14176f3abe111ac39ffe

**Comment by razvanpopadev** [comment]
Hi @josvanotterloo 
Issue had been solved. Please confirm.

Regards,
Razvan

**Comment by josvanotterloo** [comment]
Confirmed. Received now.
