### ISSUE TITLE
I don't see my coins in staking. Where did they disappear to?

### ISSUE THREAD

**Issue by Puaritanec** [Kylin-Network/subport#5]
Here is my hash: [0xb9f4e8067955574152089bdf306d5469ee88cf575702ab14b00809bc09fa5a42](url)
Help solve the problem. Thanks in advance.

**Comment by ncodespot** [comment]
Hey @Puaritanec, from the transaction hash, we found that you staked all the KYL you owned(2,005.53 KYL) successfully
https://etherscan.io/tx/0xb9f4e8067955574152089bdf306d5469ee88cf575702ab14b00809bc09fa5a42
the KYL staked was transfered to the contract https://etherscan.io/address/0xb74eb10e8a183cade3dae09d3265998e75fba37a#readContract

**Comment by Puaritanec** [comment]
Problem solved. I withdrawal all.
