### ISSUE TITLE
No PCHU Airdrop + Unable to View Staked KYL

### ISSUE THREAD

**Issue by KhanOfCrypto** [Kylin-Network/subport#50]
Hi Guys

I have two issues which I hope you can help with:

1) I'm unable to unstake my KYL tokens from the staking platform. What steps can I follow to get access to my tokens again?

2) Is there any way for me to get my PCHU airdrop even though my KYL tokens were staked? I did do the wallet handshake with the following Polkadot.JS wallet address:

5CUW3Zm8zuZRfDkBS64LQaDqmJQdNhGurbydchK4WChnHhGy

Hope you guys can help
Thanks in advance

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
please use this site to access your Kylin tokens.
