### ISSUE TITLE
Not able to unstake kyl

### ISSUE THREAD

**Issue by Henryasc** [Kylin-Network/subport#51]
Hello support, i tried to unstake my kyl many times using the link you sent me through email https://staking.kylin.network/stake/KYL
It shows my kyl balance, but im still unable to withdraw. 
It shows me "transaction error no address associated with hostname"
My trust wallet address: 0x498235B0b66111c8805C409B56F0D7d37DC24ceC 
Any suggestions? 
Thanks for your help!

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
please copy and paste this site into your wallet browser. Your Kylin tokens will be found here.
