### ISSUE TITLE
Cannot withdraw staked KYL from https://staking.kylin.network/stake/KYL

### ISSUE THREAD

**Issue by sonpham2807** [Kylin-Network/subport#53]
I can not withdraw staked KYL from https://staking.kylin.network/stake/KYL
Everytime I try to withdraw, it always looks like pending.
Please fix the problem.
My wallet address : 0xD1cD21C1C90Cdc77781086f193F98BC8BaC9392f

![image](https://user-images.githubusercontent.com/116014593/197923075-58ea7203-759e-4394-b764-9f352fce658e.png)

**Comment by STOOV1** [comment]
I understand you have ETH but you may need to increase your gwei, or try on a different browser.

**Comment by STOOV1** [comment]
This site is active. Were you able to get your end to work?
