### ISSUE TITLE
Staked rewards claimed/staked amount issue.

### ISSUE THREAD

**Issue by Cdub3166** [Kylin-Network/subport#54]
Hi, 

I recently claimed me rewards for staking. It was only 450 units which I received, but then my original amount staked of 8435.6683 was never returned to my trust wallet and it’s not appearing on the Kyl staking page. Please advise on my missing units, thank you.

my trust wallet address for the return of the funds and hopefully some compensated units for the trouble, thank you. 

Trust wallet address for kyl on the erc20: 
0xFFfbF229cDb7F9A987fa375B5643c20cA23f2D46

rewards of 450 from staked was completed 10:54 pm est. yesterday. Thank you kyl I have big hopes for your longevity in the crypto space.

**Comment by STOOV1** [comment]
Hello Cdub3166
Can you check this site:
https://staking.kylin.network/stake/KYL
your Kylin holdings should be here for you to withdraw.

**Comment by Cdub3166** [comment]
That worked thank you

**Comment by STOOV1** [comment]
That’s great👍🏻
