### ISSUE TITLE
Staked KYL gone

### ISSUE THREAD

**Issue by sjd-1** [Kylin-Network/subport#55]
Address is: 0xa83BFBf3aCcA7d51303abBE898BD0596C975ac2a

I went on vacation, my staked KYL is gone and I missed the airdrop. It would be nice to know if I can have at least one of these issues resolved. There were around 70000 KYL or so staked.

Thank you.

**Comment by STOOV1** [comment]
Hey sjd-1
Can you copy and paste this site into your wallet browser to check on your Kylin tokens. 
https://staking.kylin.network/stake/KYL
Please get back to us to follow up. Thankyou

**Comment by sjd-1** [comment]
Thank you, that worked.

I assume there is no way to retroactively do the handshake for the airdrop?
I didn't think it was going to be such a small window of time to claim them.

**Comment by STOOV1** [comment]
There was actually 2 months it was mentioned. Glad you’ve got them.
