### ISSUE TITLE
> Hello @martijn197547 ! I was unable to find the Option 2 submitted into our requests database neither with address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 or 15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW. Also address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 has no KYL tokens hold.

### ISSUE THREAD

**Issue by martijn197547** [Kylin-Network/subport#57]
> Hello @martijn197547 ! I was unable to find the Option 2 submitted into our requests database neither with address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 or 15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW. Also address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 has no KYL tokens hold.

i don't understand:
0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 (adres trust wallet eth)

15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW (signed message)

0x6882b79cafa5b930da8646789e23f1922e360b3f249c9f2a6f4bdf14c2482e891e37c158c8722ee5deb91f9e94c593ca39befe54b81e363cf6fcf4255667b4111c (signature hash)

i did option 2: https://airdrop.kylin.network/assets/Option%202%20DEMO.mp4
![Schermafbeelding 2022-10-26 092324](https://user-images.githubusercontent.com/116562212/197961144-0c7ab67f-5534-4995-a73e-7efb613830d0.jpeg)

i get the message that it was ok.

_Originally posted by @martijn197547 in https://github.com/Kylin-Network/subport/issues/38#issuecomment-1291609949_

**Comment by razvanpopadev** [comment]
The problem is that I'm unable to get the KYL balance from address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 . Please help me with that.

**Comment by martijn197547** [comment]
> The problem is that I'm unable to get the KYL balance from address 0x03b0d0bc44a6ad1b7f954a3e5c38c6062c7c5c55 . Please help me with that.

sorry my kyl adress is: 0xEE34497b177C6283b4ecE54FD0fFbFb2243BCFdE

![Schermafbeelding 2022-10-27 085809](https://user-images.githubusercontent.com/116562212/198213050-59ae8c2e-940d-4e9c-8d27-a724c49b9a51.jpeg)

is it ok so?

**Comment by razvanpopadev** [comment]
No problem. The issue is now solved, please check your address 15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW  connected to our network https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts

**Comment by martijn197547** [comment]
> No problem. The issue is now solved, please check your address 15mdwv6EgKxqHDjcr75BZfRNdjzYunYuPjF6j33V6p1zhFtW connected to our network https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts

hello, thank you, how can i add this adress to polkadot.js.org? i dont understand.

thx
