### ISSUE TITLE
Haven't received Pichiu airdrop 

### ISSUE THREAD

**Issue by file20** [Kylin-Network/subport#58]
I have registered my wallet long time ago but no airdrop received . wallet address: 5Fpwgrs2igq5XnrMpqGZpBAmTMPGKKhWGMWUWAFXe6qu4z2k

**Comment by razvanpopadev** [comment]
Hello,
Unfortunately your address 5Fpwgrs2igq5XnrMpqGZpBAmTMPGKKhWGMWUWAFXe6qu4z2k was not submitted into the airdrop handshake we've announced. 

Regards,
Razvan

**Comment by file20** [comment]
The announcement I have seen in telegram has been about a registration of my wallet: the one where I am holding my KYL tokens and the one where I want to get the Pichiu, don't really know what means handshake and why you made this airdrop so complicated, keep in mind that many of us (the investors) are really busy guys and don't have time to check on daily/weekly base how many announcements you are making about any airdrop,if you respect the guys who is spending money on a high, very high risk projects like yours just keep it simple mate (a free advice)
