### ISSUE TITLE
I have registered my wallet long time ago but no PCHU airdrop received

### ISSUE THREAD

**Issue by ghost** [Kylin-Network/subport#59]
I have registered my wallet long time ago but no airdrop received . wallet address: 5FpbrxMPXRWj9KqQzXMWBzdvK7JU3rY883K8gUcnRzps7fb4

**Comment by razvanpopadev** [comment]
Hello @truckkundoko 
Issue had been solved. Please confirm.

Regards,
Razvan

**Comment by ghost** [comment]
Verified. Thanks!
