### ISSUE TITLE
Havn't received PCHIU airdrop

### ISSUE THREAD

**Issue by tellmewenser** [Kylin-Network/subport#60]
Hello, I've not received the PCHIU airdrop.
I did the handshake in time.
My adresses : 
eth 0xF22f0eca618e2532AAB4169d265Da1EBD9624ad5
polk FZaX6j2dHP3MQQkKAwfpZX2e38T5yecKZCQvCYzcRK1edQ1
acc on pchiu : 5E4tiSw4mpBxP1QcHCjvKnpAggYGT2vsnHRmbz2B61WTjffV

Thanks for your help

**Comment by razvanpopadev** [comment]
Hello @tellmewenser 
Your airdrop tokens had been transferred to 5F3xrnP9zvN7bkbJYU8cvcA2VSrDHJqRsBMfXYH38d6WuSwX (address submitted by you in the handshake process). This address is the same as polk FZaX6j2dHP3MQQkKAwfpZX2e38T5yecKZCQvCYzcRK1edQ1 just the prefix differs.

Regards,
Razvan
