### ISSUE TITLE
PCHIU airdrop

### ISSUE THREAD

**Issue by Pashagraf** [Kylin-Network/subport#61]
Hello team, I've not received the PCHIU airdrop. Can't find any okens in my wallet
Can you chek?
My adresses :
eth: 0xa03a88989086E84E91e7ff79b69a4ED9e18E1539
dot: 16DBh5fBcih3X7uqJUjgvprxPUBcum4LmrCouyRuRPEgHdEe

**Comment by razvanpopadev** [comment]
Hello @Pashagraf 
Your airdrop tokens had been sent to address 16DBh5fBcih3X7uqJUjgvprxPUBcum4LmrCouyRuRPEgHdEe. Please check by connecting your PoladotJS wallet to Pichiu Network or by using this link: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts

Regards,
Razvan

**Comment by Pashagraf** [comment]
Hello @inodelisia 
I use that link, but couldn't find any Pichiu account. 
So I decide to create a new Pichiu account 
5F9TPcawmQzw92BaiGfoTr41wCxJyraS4NYLPF3YseHaJBfR

Regards,
Pavlo
