### ISSUE TITLE
Havn't received PCHIU airdrop

### ISSUE THREAD

**Issue by Joy202222222222** [Kylin-Network/subport#62]
I made the handshake.
My erc wallet address: 0x18ACeEfFBb66a7c5A43c0C60C954Aa2810127AB1
My pichu wallet address: 5CZpRVge9apk5Jmiaz7y24cv5s7kV2BMgV3sSG4xoAD88qLY.
Thank you.

**Comment by razvanpopadev** [comment]
Hello @Joy202222222222 
Your airdrop tokens had been sent to address 5CZpRVge9apk5Jmiaz7y24cv5s7kV2BMgV3sSG4xoAD88qLY. Please check by connecting your PoladotJS wallet to Pichiu Network or by using this link: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts

Regards,
Razvan
