### ISSUE TITLE
Math wallet 

### ISSUE THREAD

**Issue by BuckarooBanzai1** [Kylin-Network/subport#63]
I use math wallet for my polkadot, so that's what I used for option one along with my metamask wallet where my kylin is located.... Did I make a mistake, will I not receive pichiu?
MetaMask kylin address 
0x8c510875eF3B376Cce62468279B87b20913420d0
Math wallet polkadot address
12QbPFFkiTEuCUgaphYCD4F1ryYd4ktbKGkvvCxx4mDCMabX

**Comment by razvanpopadev** [comment]
Hello @BuckarooBanzai1 
Your airdrop tokens had been already transferred. Please check your PolkadotJS wallet connected to our Pichiu Network on Kusama Relay chain: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts

**Comment by BuckarooBanzai1** [comment]
I don't think I set up a polkadotJS wallet, is it too late to do so?
