### ISSUE TITLE
Pichiu Airdrop help please 🙏 

### ISSUE THREAD

**Issue by Kaari-h** [Kylin-Network/subport#64]
Hi Team, would appreciate help with the Pichiu airdrop for holding Kylin in my Metamask

Metamask Address:
0x3989e4E82C96AFb0755FD2aDee487cceCDBEFD2E

Fearless Address:
5H3pxEe72U2u4RXGo7tNUy2LK2ziZ7u7pzx8YyiHWEDVJ8cc

Many Thanks & well wishes for all your future endeavours.

**Comment by razvanpopadev** [comment]
Hello @Kaari-h 
Unfortunately there is no such address in our airdrop request lists.

Reagards,
Razvan
