### ISSUE TITLE
Haven't received PICHU

### ISSUE THREAD

**Issue by doctor51784** [Kylin-Network/subport#65]
Wallet 162kkytztwfwskj9yfpnefdznjziqfwdoovr6c6p3nzjl6jh

**Comment by razvanpopadev** [comment]
Hello @doctor51784 
Your airdrop tokens had been already transfer, Please check your wallet connected to our Pichiu Network on Kusama Relay chain: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts

Regards,
Razvan
