### ISSUE TITLE
Didn't received airdrop pichu

### ISSUE THREAD

**Issue by Joy202222222222** [Kylin-Network/subport#66]
Hello,
I made the handshake of 2 my erc20 wallets (0x18ACeEfFBb66a7c5A43c0C60C954Aa2810127AB1, and 0xA6a0D27c6ec00276F1e62C3252d08120d95A6402) with my 1 substrate wallet (5CZpRVge9apk5Jmiaz7y24cv5s7kV2BMgV3sSG4xoAD88qLY). Now, i just got only airdrop for 1 erc20 wallet (0xA6a0D27c6ec00276F1e62C3252d08120d95A6402). 
I created 2 time issues on Kylin- Network/subport and you said "solved issues" and "close issues". 
Please check clearly my problem. 
Thank a lot.

**Comment by razvanpopadev** [comment]
Hello @Joy202222222222 
Issue had been solved.

Regards,
Razvan
