### ISSUE TITLE
Pichu

### ISSUE THREAD

**Issue by Dcsmacedo** [Kylin-Network/subport#67]
Didn’t receive my airdrop
![045B3D2D-D272-4986-9644-6697E96A352D](https://user-images.githubusercontent.com/116793058/198220258-2f2c9951-5036-4b0d-91fb-1bda00abd4c6.png)

**Comment by razvanpopadev** [comment]
Hello @Dcsmacedo 
In the "Signed message" field should have been your substrate PCHU address as stated in the airdrop instruction. Unfortunately we cannot do anything to solve this situation now.

Regards,
Razvan
