### ISSUE TITLE
Pchu Airdrop not received

### ISSUE THREAD

**Issue by godzilla1000** [Kylin-Network/subport#68]
I had my KYL staked on https://staking.kylin.network/ but during the airdrop period, the site was down. Not sure if that's the reason. I also did the instructions successfully with "https://airdrop.kylin.network/"

**Comment by godzilla1000** [comment]
5DUGDem1yQQFeaBF9E4Pro1zSoa8BmhHqEVpTPjPJCjfE9wp
0xB47910b96d24B56F23505BE1C1953566d55f4cFE

**Comment by razvanpopadev** [comment]
Hello @godzilla1000 
Issue had been solved. Please confirm.

Regards,
Razvan

**Comment by godzilla1000** [comment]
> Hello @godzilla1000 Issue had been solved. Please confirm.
> 
> Regards, Razvan

Confirmed! Thanks
