### ISSUE TITLE
Pichiu Airdrop can't find tokens

### ISSUE THREAD

**Issue by Pashagraf** [Kylin-Network/subport#69]
Hello
I use link, that you give me  (issue#61) https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts
but couldn't find any Pichiu account.
So I decide to create a new Pichiu account:
5F9TPcawmQzw92BaiGfoTr41wCxJyraS4NYLPF3YseHaJBfR
My other adresses :
eth: 0xa03a88989086E84E91e7ff79b69a4ED9e18E1539
dot: 16DBh5fBcih3X7uqJUjgvprxPUBcum4LmrCouyRuRPEgHdEe

Regards,
Pavlo

**Comment by razvanpopadev** [comment]
Hello,
Please add your dot: 16DBh5fBcih3X7uqJUjgvprxPUBcum4LmrCouyRuRPEgHdEe to https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts this will solve the problem. The tokens had been already transferred to 16DBh5fBcih3X7uqJUjgvprxPUBcum4LmrCouyRuRPEgHdEe .

Regards,
Razvan

**Comment by Pashagraf** [comment]
Thank you very much @inodelisia!  I find it!

Regards,
Pavlo
