### ISSUE TITLE
Not received pichiu airdrop

### ISSUE THREAD

**Issue by strunziii** [Kylin-Network/subport#70]
Hello, I've not received the PCHIU airdrop. I did the handshake in time.

signature: 
https://etherscan.io/verifiedSignatures?q=0xF0934B86ae615D7e51C9ad8D2F9eE9086451d1B4
signature hash: 0x7807197c09bcbcc1c5ec41eb0fca546d09a656c6730d64445f441e2af091c4286cd050d0b3de252e30a532dfe3390285be9560720f8ee5cc13682f113fbcf7f81b
acc on pichiu: 5GKeH8Vpe7uuV6Ez1mWFWFtYBmVyHC6rpyF1cYdKwqjNkH1B

Thanks for your help

**Comment by razvanpopadev** [comment]
Hello @strunziii 
Yor tokens had been transferred to 15wXmGZMNAkB8Ni3ZtosRRRjXHz1p6CDC7ZjxpdJwmuzv7PY (probably your dot address, but can be used also on our network Pichiu)

Regards,
Razvan
