### ISSUE TITLE
PCHIU Airdrop not received

### ISSUE THREAD

**Issue by Starfox1985** [Kylin-Network/subport#71]
Hello,
I've not received the PCHIU airdrop. I did the handshake in time.

https://etherscan.io/verifySig/10981

acc on pichiu: 5CkNCb782MDrwwtp5mYCuauRrMiqhcyGdXYF3zG5dfMpjfaj

signature hash: 0x3e39dcb2c0e3a3aad4e27c047533c0c745a3192ad569aefa8e68f8e4fe17f7ef2b87bc05cf4909cf85665d7fbeb6892d3dfdfff8b38e4e8b9add56db51bb83cb00

Thx for support!

**Comment by razvanpopadev** [comment]
Hello @Starfox1985 
You airdrop tokens had been already transferred to 14YTU11CczbiLu4dviaQdh5wUrekFxjfF6SQt7xioshWRiTV (this address was used in the handshake process). Please add this address to our network (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.kylin-node.co.uk#/accounts)

Regards,
Razvan
