### ISSUE TITLE
Pichiu Airdrop Issue

### ISSUE THREAD

**Issue by Jayce231** [Kylin-Network/subport#72]
Hi Team,

Plz help me my case, I did a mistake when register Pichiu airdrop for KYL holder by 2x filling the same ETH address without filling Polkadot adress so I cant receive Pichiu token.

this is the ETH address that holding KYL 0xacad464EF6638aaaE4E9CC9991A1BD2b0F77eB12
And this is the new polkadot address which i just created in case Tech team can help 5DX1hBpCTNUMrnyy7N9MEr2ynRgoYRjbfvTPheVzSiAy7tT8

**Comment by razvanpopadev** [comment]
Hello @Jayce231 
Issue had been solved, please confirm.

Regards,
Razvan
