### ISSUE TITLE
Yet to receive Pchiu Airdrop 

### ISSUE THREAD

**Issue by donuttos** [Kylin-Network/subport#73]
Previously have open a ticket to confirm my substrate account for the handshake, yet still receive the airdrop, please check
Substrate: 5DqXGNFFRNn89zCrTSj8VSh2auxHnBr1FT29femG6rMUfzur
Kylin metamask: 0x4208811902feBd12E624721C6D81D2a081da738B

**Comment by BasdeSchipper** [comment]
Hi Donuttos,
Can you check here please: https://polkadot.polkaholic.io/ 
Enter your wallet address 5Dxxxxx and press home.
You should see all you token in all Polkadot chains.
Cheers, Bas

**Comment by donuttos** [comment]
![image](https://user-images.githubusercontent.com/116186367/198880533-0bdb1b24-3e5d-443e-96b0-9346db8c3d84.png)

I got this instead

**Comment by BasdeSchipper** [comment]
Did you sign in with your extension?
You need to approve the site to access your Polkadot wallet.

**Comment by donuttos** [comment]
Can you screenshot an example to show me how it should look like?

**Comment by donuttos** [comment]
![image](https://user-images.githubusercontent.com/116186367/198883247-d0eb8942-83d7-4ca6-932a-de34852875c2.png)

**Comment by BasdeSchipper** [comment]
Thanks, seem the Airdrop didn’t happen.
@sylvaincormier can you have a look?

**Comment by razvanpopadev** [comment]
Hello @donuttos 
Issue had been solved, please confirm. The cause was your KYL balanced not visible.
Thank you @BasdeSchipper for support!

Regards,
Razvan
