### ISSUE TITLE
Also didn't receive the PCHU airdrop

### ISSUE THREAD

**Issue by Panemetcircensis** [Kylin-Network/subport#76]
Hi Kylinteam,
I didn't get an airdrop either. My last issue was simply closed without an answer. 
Could you please check my case or explain to me what I did wrong? The handshake with "Option 1" worked, maybe I activated the kusama address too late? However, the address has remained the same.
Here is my ETH adress: 0x61e40273110EABc3b15588C5Fcc80eA4461F51B7

This was my substrate adress:
Dd388rvfrqRkVHrDDrXijL1xaAKLFsym9aA13r7wZcXNfTj.

Thanks in advance and best regards,
Chris

**Comment by Andrey810** [comment]
good afternoon, apparently you specified the wrong address format substrate, the pichiu address starts with 5,,,,,,,,,,,,,,,,,,,,,,,,,,,

**Comment by Panemetcircensis** [comment]
Thanks a lot Andrey810 for your helpful answer.
I was probably just too stupid to use my mobile device wallet properly, I only specified the KSM network (and laziness is punished: polkadot.js not installed on desktop browser).
In any case, it is strange that the "handshake" was confirmed without any problems.
Unfortunately, I don't know anything about the Kusama network, for me it's higher mathematics (and I've just mastered basic arithmetic). 
Think I've made my bed, now I must lie in it...

**Comment by BasdeSchipper** [comment]
Hi Chris, 

Your PICHIU is in your PICHIU wallet:
![image](https://user-images.githubusercontent.com/109458844/200052666-9f9660c2-7172-4e36-9c2e-a7b3e1ae4797.png)

https://polkaholic.io/account/5D7RTpX43VpVzqUQSX3Upmy1oyt5Xb4oJmjQcPaATmQ2dchm?group=overview&chainfilters=all

Cheers Bas

**Comment by Panemetcircensis** [comment]
Hello Bas, that's wonderful, then everything worked out after all, great!!
