### ISSUE TITLE
PICHIU Airdrop, did not receive

### ISSUE THREAD

**Issue by jeckt84** [Kylin-Network/subport#78]
Hello,

My KYL address is 5GE1KPuwwvz6jy3QZJwnUTLJRreFxyWdapPktai9YdULHF87
ERC20 address: 0x99e5f58Fbb54D8Ef015943E930DD1F091A0fB573
Polkadot Crowdloan 15AJTjB1oiFaBW3vWwznccATHUdufH4mfK8F3shW6iVrTrqk

I did not get any distribution.  Please advise.

Thank you,
Mark

**Comment by BasdeSchipper** [comment]
Hi Mark, 

Your PICHIU is distributed in your PICHIU wallet:
![image](https://user-images.githubusercontent.com/109458844/200052876-62757ad0-d934-43dc-9ff8-5e61761a5380.png)

https://polkaholic.io/account/5GE1KPuwwvz6jy3QZJwnUTLJRreFxyWdapPktai9YdULHF87?group=overview&chainfilters=all

Cheers, 
Bas

**Comment by jeckt84** [comment]
Thank you, I was looking for it under Polkadot parachain, it's listed in Kusama
