### ISSUE TITLE
PCHU airdrop

### ISSUE THREAD

**Issue by tyvian** [Kylin-Network/subport#85]
Dears, due to the circumstances I've missed handshake period, but my KYL were staked for a while.
Could You please kindly check the case and support me, thanks a lot in advance...

ERC-20: 0xd737F6D44587a1E67513Cbbc7263a2684Fe9BA12
substrate: 5H4CRDNc3tUtidDrrtqBt5JxMFA3bB2REDjskMGi4tSePMUg

**Comment by STOOV1** [comment]
👋🏻 If you’ve missed the handshake, then this opportunity won’t be available to you. There are Incentivized community programs available soon. Thank you.

**Comment by tyvian** [comment]
hi, it was imprudent for me to miss this handshake process, yeah 

but look - we still have the war in our country, guess it is validity reason for non checking project news daily, especially if the tokens were staked at official Kylin platform. The snapshots were taken in past - Kylin does have the records about me.

just please check my case with devs, I’m sure it could be solved technically manually easy, just question of a little time and willing from your side… (all details info could be provided upon request asap)
