### ISSUE TITLE
Do not see my Kylin

### ISSUE THREAD

**Issue by tuandinh1810** [Kylin-Network/subport#9]
Hi Kylin team,
To day I login https://staking.kylin.network/
I don't see my Kylin (staked+reward)
here is my address 0x5038934c04dbB61CbdD67175587209ef7d0F40d1

**Comment by Drabo6** [comment]
try this adress https://staking.kylin.network/stake/KYL

**Comment by STOOV1** [comment]
https://staking.kylin.network/stake/KYL
Hello
Please copy and paste this into your ERC20 wallet browser to access your Kylin.
